Repository Eccoar/2020.2-Eccoar_Complaint, pull requests merged in 2021-05, with the labels that each got.

#18 Solve #153 Retirada de denúncia
  src/controllers/ControllerComplaint.ts
  src/entity/Complaint.ts
  src/entity/Votes.ts
  src/migration/1620151058075-DeleteCascade.ts
  src/repositories/ComplaintRepository.ts
  src/repositories/VotesRepository.ts
  src/routes.ts
  src/server.ts
  src/services/S3Service.ts
  test/controller.test.ts
  test/repository.test.ts
Labels: Backend, MDS

#17 Solve #139 Retirar upvote e voto de confirmação
  package-lock.json
  src/controllers/ControllerComplaint.ts
  src/migration/1618526567509-CreateComplaint.ts
  src/migration/1618529825437-CreateVote.ts
  src/repositories/VotesRepository.ts
  src/routes.ts
  src/utils/ComplaintWithVote.ts
  test/complaintRepository.test.ts
  test/controller.test.ts
  test/voteRepository.test.ts
Labels: Backend, MDS

#24 Hotfix #191 Flaggr e quantidade de votos
  src/controllers/ControllerComplaint.ts
  src/utils/ComplaintUpvote.ts
  src/utils/ComplaintVote.ts
  src/utils/ComplaintVoteConfirmed.ts
  test/complaintValidate.test.ts
  test/controller.test.ts
  test/voteRepository.test.ts
Labels: HOTFIX

#19 Solve #167 Listar denúncias próximas do usuário
  .eslintrc
  src/controllers/ControllerComplaint.ts
  src/repositories/ComplaintRepository.ts
  src/utils/ComplaintWithVoteAndDIstance.ts
  test/complaintRepository.test.ts
  test/controller.test.ts
Labels: Backend, Denúncias, História de usuário, MDS, US

#25 Solve #227 HOTFIX Sonar URL
  .gitlab-ci.yml
Labels: ANALYTICS, EPS, HOTFIX
