Repository Eccoar/2020.2-Eccoar_Complaint, pull requests merged in 2021-04, with the labels that each got.

#10 Solve #125 US17 Página de detalhamento de denúncia
  src/controllers/ControllerComplaint.ts
  src/repositories/ComplaintRepository.ts
  src/routes.ts
  test/controller.test.ts
Labels: Backend, Denúncias, História de usuário

#9 Solve #124 Envio de e-mails
  db/seeds/ComplaintSeed.ts
  db/seeds/complaintData.ts
  package-lock.json
  package.json
  src/controllers/ControllerComplaint.ts
  src/repositories/ComplaintRepository.ts
  src/routes.ts
  src/utils/Category.ts
  src/utils/ComplaintWithVote.ts
  test/controller.test.ts
  test/repository.test.ts
Labels: Backend, Comunicação com orgãos, Denúncias, História de usuário

#15 Solve #159 Configurar migrações
  docker-compose.yml
  package.json
  src/migration/1618526567509-CreateComplaint.ts
  src/migration/1618529825437-CreateVote.ts
  tsconfig.json
Labels: ARQ, EPS, MEDIUM

#16 Solve #156 Configuração Sentry
  package.json
  src/server.ts
  src/utils/sentry.ts
Labels: ANALYTICS, EASY, EPS
